[package]
disabled = true

[character]
format = "[λ ❯](bold green) "
success_symbol = "[λ ❯](bold green) "
vicmd_symbol = "[λ ❯](bold blue) "
error_symbol = "[λ 💥](bold red) "

[git_branch]
format = " [$symbol$branch]($style) "
symbol = "🍣 "
style = "bold yellow"
truncation_symbol = ""

[status]
style = "bg:red"
symbol = "💥 "
format = '[\[$symbol$status\]]($style) '

[git_status]
conflicted = "⚔️ "
ahead = "🏎️ 💨 ×${count}"
behind = "🐢 ×${count}"
diverged = "🔱 🏎️ 💨 ×${ahead_count} 🐢 ×${behind_count}"
untracked = "🛤️  ×${count}"
stashed = "📦 "
modified = "📝 ×${count}"
staged = "🗃️  ×${count}"
renamed = "📛 ×${count}"
deleted = "🗑️  ×${count}"
style = "bright-white"
format = "$all_status$ahead_behind"

[git_state]
progress_divider = " of "

[time]
disabled = false
style ="bold green"

[username]
show_always = true

[aws]
disabled = true