code --install-extension abusaidm.html-snippets
code --install-extension adamhartford.vscode-base64
code --install-extension andyyaldoo.vscode-json
code --install-extension batisteo.vscode-django
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension danwahlin.angular2-snippets
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension daylerees.rainglow
code --install-extension dbaeumer.vscode-eslint
code --install-extension DigitalBrainstem.javascript-ejs-support
code --install-extension donjayamanne.githistory
code --install-extension donjayamanne.python-extension-pack
code --install-extension DotJoshJohnson.xml
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension eg2.vscode-npm-script
code --install-extension erd0s.terraform-autocomplete
code --install-extension eriklynd.json-tools
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension hashicorp.terraform
code --install-extension hex-ci.stylelint-plus
code --install-extension humao.rest-client
code --install-extension jasonnutter.search-node-modules
code --install-extension johnpapa.Angular2
code --install-extension magicstack.MagicPython
code --install-extension mathiasfrohlich.Kotlin
code --install-extension Mikael.Angular-BeastCode
code --install-extension ms-azuretools.vscode-azureterraform
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-vscode.azure-account
code --install-extension naumovs.color-highlight
code --install-extension quicktype.quicktype
code --install-extension ritwickdey.LiveServer
code --install-extension robinbentley.sass-indented
code --install-extension run-at-scale.terraform-doc-snippets
code --install-extension scala-lang.scala
code --install-extension skyapps.fish-vscode
code --install-extension steoates.autoimport
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension tomoki1207.pdf
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vscoss.vscode-ansible
code --install-extension waderyan.nodejs-extension-pack
code --install-extension wholroyd.jinja
code --install-extension xabikos.JavaScriptSnippets
code --install-extension yzhang.markdown-all-in-one
code --install-extension Zignd.html-css-class-completion
